---
title: "Ahlmann-Eltze & Huber 2023"
output: html_document
---

# Load packages
```{r}
library(SingleCellExperiment)
library(muscat)
library(Matrix)
library(tidyverse)
library(fastRUVIII)
source("/home/users/allstaff/liu.ne/scMultiOmics-normalization/transformGamPoi_Paper_benchmark/benchmark/src/consistency_benchmark/download_helper.R")
source("/home/users/allstaff/liu.ne/scMultiOmics-normalization/transformGamPoi_Paper_benchmark/benchmark/src/transformations/transformation_helper.R")
library(ggplot2)
library(ggbeeswarm)
library(ggh4x)
library(dplyr)

set.seed(1)

result_dir <- "/vast/scratch/users/liu.ne/transformGamPoi_simulation_data"

```


# Setup parameters
```{r}

knns <- c(10, 20, 50)
pcs <- c(5, 10, 50)

simulations <- c("Dyngen", "scDesign", "Muscat", "Linearwalk", "Randomwalk")
data_path <- "/vast/scratch/users/liu.ne/transformGamPoi_simulation_data/"
file_paths <- unlist(lapply(simulations, function(sim) {
  list.files(path = data_path, pattern = paste0("^", sim, "_seed_\\d+\\.rds$"), full.names = TRUE)
}))
file_names <- unlist(lapply(simulations, function(sim) {
  list.files(path = data_path, pattern = paste0("^", sim, "_seed_\\d+\\.rds$"), full.names = FALSE)
}))

# Excluding Sanity (environment shenanigans because not implemented in R)
transformations <- c(
  "logp1", 
  "logp1_hvg", 
  "logp1_zscore", 
  "logp1_hvg_zscore",
  "logp_cpm", 
  "logp1_size_normed", 
  "acosh", 
  "logp_alpha",
  "pearson", 
  "pearson_clip", 
  "pearson_analytic", 
  "sctransform",
  "rand_quantile", 
  "pearson_clip_hvg", 
  "pearson_clip_zscore",
  "pearson_clip_hvg_zscore", 
  "normalisr_norm", 
  #"sanity_map",
  #"sanity_dists", 
  #"glmpca", 
  "raw_counts", 
  "scaled_raw_counts"
)


trans_families <- list(
  delta_method = c(
    "logp1", 
    "acosh", 
    "logp_alpha", 
    "logp_cpm", 
    "logp1_size_normed", 
    "logp1_hvg", 
    "logp1_zscore",  
    "logp1_hvg_zscore"),
  glm_residual = c(
    "pearson_clip", 
    "sctransform", 
    "pearson_analytic", 
    "rand_quantile", 
    "pearson",  
    "pearson_clip_hvg", 
    "pearson_clip_zscore", 
    "pearson_clip_hvg_zscore"),
  latent_expr = c(
    "sanity_map", 
    "sanity_dists", 
    "dino", 
    "normalisr_norm"),
  count_model = c(
    "glmpca", 
    "newwave"),
  negative_control = c(
    "raw_counts", 
    "scaled_raw_counts"),
  RUV = 'fastRUVIII') %>%
  enframe() %>%
  unnest(value) %>%
  transmute(transformation = value, family = name)

alphas <- list(
  logp1 = FALSE,
  logp1_hvg = FALSE,
  logp1_zscore = FALSE,
  logp1_hvg_zscore = FALSE,
  logp_cpm = FALSE,
  logp1_size_normed = FALSE,
  acosh = c(0.05, 0, TRUE),
  logp_alpha = c(0.05, 0, TRUE),
  pearson = c(0.05, 0, TRUE),
  pearson_clip = c(0.05, 0, TRUE),
  pearson_analytic = c(0.05, 0, TRUE),
  sctransform = c(0.05, 0, TRUE),
  rand_quantile = c(0.05, 0, TRUE),
  pearson_clip_hvg = c(0.05, 0, TRUE),
  pearson_clip_zscore = c(0.05, 0, TRUE),
  pearson_clip_hvg_zscore = c(0.05, 0, TRUE),
  normalisr_norm = FALSE,
  sanity_map = FALSE,
  sanity_dists = FALSE,
  glmpca = c(FALSE, 0.05),
  raw_counts = FALSE,
  scaled_raw_counts = FALSE
)

sim_params <- tidyr::tibble(  
  data = file_names,
  path = file_paths
  )

sim_params <- tidyr::crossing(
  sim_params,
  trans = transformations
)

#saveRDS(sim_params, file = "/home/users/allstaff/liu.ne/scMultiOmics-normalization/slurm_benchmarking_scripts/simulation_params.rds")

```

# Now generate the data via slurm jobs
# This might take a few hours!
```{r}
setwd("/home/users/allstaff/liu.ne/scMultiOmics-normalization/slurm_benchmarking_scripts")
system("sbatch generate_simulation_data.sh")

```

# Now compute the transformations
```{r}
setwd("/home/users/allstaff/liu.ne/scMultiOmics-normalization/slurm_benchmarking_scripts")
system("sbatch transform_simulated_data.sh")
system("squeue -u liu.ne")
system("sacct -j 23597532")

```

# Calculate KNNs after running the slurm jobs
```{r}
library(stringr)
library(dplyr)

# Step 1: List all result file paths
files <- list.files(
  "/vast/scratch/users/liu.ne/transformGamPoi_Output/results/simulation_results/transformed_knns", 
  full.names = TRUE)

# Sort transformations so longer names are matched first
transformations_sorted <- transformations[order(nchar(transformations), decreasing = TRUE)]

# Build regex pattern
pattern <- paste0("(", paste(transformations_sorted, collapse = "|"), ")")

# Step 2: Extract metadata
file_info <- tibble(path = files) %>%
  mutate(
    filename = basename(path),
    simulation = str_extract(filename, "^[^_]+"),  # e.g. Dyngen
    seed = str_extract(filename, "(?<=_seed_)\\d+"),
transformation = str_extract(filename, pattern),
    group = paste(simulation, seed, transformation, sep = "_")
  )

# Step 3: Split into named list
grouped_files <- split(file_info, file_info$group)

saveRDS(
  grouped_files, 
  "/home/users/allstaff/liu.ne/scMultiOmics-normalization/slurm_benchmarking_scripts/simulation_result_paths.rds")

```

# Compute the KNN overlaps
# This might take 24+ hours!!!
```{r}
setwd("/home/users/allstaff/liu.ne/scMultiOmics-normalization/slurm_benchmarking_scripts")
system("sbatch calculate_simulation_overlaps.sh")
system("squeue -u liu.ne")
system("sacct -j 23608204")

```


# RUVIII Exploration
```{r}

cluster_res <- c(0.1, 0.5, 1)
ruv_params <- tidyr::crossing(seed = 1:5, simulations, cluster_res)

# REQUIRES MANUAL CHANGING AND EXPLORING CLUSTERS
seed <- 3
simulation <- "Dyngen"
  
ground_truth_paths <- paste0(
  "/vast/scratch/users/liu.ne/transformGamPoi_simulation_data/", simulation,"_seed_",1:5,".rds")

ground_truth_data <- readRDS(ground_truth_paths[[seed]])
matrix <- ground_truth_data$UMI

hvgs <- Seurat::VST(matrix, nselect = 0.2 * nrow(matrix))

pca <- BiocSingular::runSVD(
  t(matrix[hvgs$variable,]), center= T, scale = F, 
  BSPARAM = BiocSingular::bsparam(), 
  k = 20)

umap <- uwot::umap(pca$u, n_neighbors = 20, n_components = 3)

neighbors <- Seurat::FindNeighbors(as(pca$u,'dgCMatrix'), k.param = 20)
clusters <- Seurat::FindClusters(neighbors$snn, resolution = 0.2)

plotly::plot_ly(
  data = as.data.frame(umap), 
  x = ~V1, y = ~V2, z = ~V3, color = unlist(clusters), 
  type = 'scatter3d', mode = 'markers',
  marker = list(size = 4, opacity = 0.8)) %>%
  plotly::layout(
    title = "3D UMAP",
    scene = list(
      xaxis = list(title = 'V1'),
      yaxis = list(title = 'V2'),
      zaxis = list(title = 'V3')
      )
    )

```

# RUVIII normalization
# again this might take many hours
```{r}
setwd("/home/users/allstaff/liu.ne/scMultiOmics-normalization/slurm_benchmarking_scripts")
system("sbatch run_fastRUVIII_simulation.sh")
system("squeue -u liu.ne")
system("sacct -j 23606587")

```

# Bind the final result tsv
```{r}

result_paths <- list.files(
  "/vast/scratch/users/liu.ne/transformGamPoi_Output/results/simulation_results/knn_overlap_metrics/", 
  full.names = TRUE)

res <- lapply(result_paths, function(res_id){
  res <- read_tsv(res_id, col_types = list(alpha = "character"), show_col_types = FALSE)
  # duration <- read_tsv(file.path(pa$working_dir, "duration", res$transformation_id), show_col_types = FALSE))
}) %>%
  bind_rows()

write_tsv(res, "/vast/scratch/users/liu.ne/transformGamPoi_Output/results/simulation_results/final_metrics.tsv")
res <- read_tsv("/vast/scratch/users/liu.ne/transformGamPoi_Output/results/simulation_results/final_metrics.tsv")


```

# Filtering
```{r,fig.width= 5, fig.height= 6}

res_main <- res %>%
  filter(alpha %in% c("1","0", "TRUE", "FALSE", 1, NA, 0)) %>%
  #filter(seed %in% 1:5) %>%
  #filter(simulator %in% c("Linearwalk")) %>%
  #filter(pca_dim == 10) %>%
  filter(knn %in% 50) %>%
  mutate(knn_recovery = mean_knn_overlap / knn) %>%
  group_by(simulator, seed, knn) %>%
  mutate(knn_recovery = knn_recovery / mean(knn_recovery)) %>%
  tidylog::left_join(trans_families)


p <- ggplot(res_main, aes(x = knn_recovery, y = transformation)) +
  # Grey points
  geom_quasirandom(color = "grey", size = 1, alpha = 0.2) +
  # Colored mean points (no CI)
  stat_summary(
    fun = mean,
    geom = "point",
    aes(color = family),
    size = 3
  ) +
  geom_vline(xintercept = 1, linetype = "dashed", color = "grey40") +
  scale_x_continuous(name = "Relative k-NN overlap", breaks = c(0.5, 1, 1.5)) +
  coord_cartesian(xlim = c(0, 2)) +
  scale_color_brewer(palette = "Dark2") +
  theme_minimal(base_size = 10) +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_text(size = 9),
    panel.grid = element_blank(),
    panel.border = element_rect(color = "grey30", fill = NA, size = 0.1),
    legend.position = "none",
    plot.title.position = "plot"
  ) +
  ggh4x::facet_grid2(rows = vars(family), scales = "free_y", space = "free_y", switch = "y") +
  theme(strip.text.y.left = element_blank())

p

```



