---
title: "WNN CITE seq & 10x Multiome"
author: "Neal Liu"
date: "2024-02-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries & our own helper functions

```{r}

library(Seurat)
library(SeuratData)
library(cowplot)
library(dplyr)
library(ggplot2)
library(devtools)
library(umap)

# load our helper functions from github
devtools::source_url('https://raw.githubusercontent.com/Neal-Liu1/Multi-omics-integration/main/Helper_functions.R')

# devtools::install_github("sqjin/scAI")
library(scAI)
library(tiltedCCA)
library(MOFA2)

# ADT normalization (ADTnorm, DSB, CLR)
# remotes::install_github("yezhengSTAT/ADTnorm")
library(ADTnorm)
library(dsb)
# for CLR
library(compositions)
# benchmark ARI, silhouette with umap, vector correlation w pca,


# for RNA normalization:
# Seurat sctransform, CCA, RPCA
# LIGER
# FastMNN
# Harmony



```

Get the bone marrow CITEseq data from seurat on the VAST scratch on the HPC

```{r}
# SeuratData::InstallData("bmcite", destdir = '/vast/scratch/users/liu.ne')
bm_data <- LoadData(ds = "bmcite")

```


```{r}
DefaultAssay(bm_data) <- 'RNA'
bm_data <- NormalizeData(bm_data) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA()
```


```{r}
DefaultAssay(bm_data) <- 'ADT'
# we will use all ADT features for dimensional reduction
# we set a dimensional reduction name to avoid overwriting the 
VariableFeatures(bm_data) <- rownames(bm_data[["ADT"]])
bm_data <- NormalizeData(bm_data, normalization.method = 'CLR', margin = 2) %>% 
  ScaleData() %>% RunPCA(reduction.name = 'apca')

```

```{r}
# Identify multimodal neighbors. These will be stored in the neighbors slot, 
# and can be accessed using bm[['weighted.nn']]
# The WNN graph can be accessed at bm[["wknn"]], 
# and the SNN graph used for clustering at bm[["wsnn"]]
# Cell-specific modality weights can be accessed at bm$RNA.weight
bm_data <- FindMultiModalNeighbors(
  bm_data, reduction.list = list("pca", "apca"), 
  dims.list = list(1:30, 1:18), modality.weight.name = "RNA.weight"
)

```

```{r}
bm_data <- RunUMAP(bm_data, nn.name = "weighted.nn", reduction.name = "wnn.umap", reduction.key = "wnnUMAP_")
bm_data <- FindClusters(bm_data, graph.name = "wsnn", algorithm = 3, resolution = 2, verbose = FALSE)

```

```{r, fig.width= 10}

p1 <- DimPlot(bm_data, reduction = 'wnn.umap', label = TRUE, repel = TRUE, label.size = 2.5) + 
  theme_minimal() +
  labs(title = 'Clusters') +
  theme(axis.line = element_line(colour = "grey83", linewidth=1.1),
          panel.border = element_rect(colour = "grey90", fill=NA, size=0.7),
          panel.grid.major = element_line(color = "grey96"),
          aspect.ratio = 1/1.05)+
  NoLegend()
p2 <- DimPlot(bm_data, reduction = 'wnn.umap', group.by = 'celltype.l2', label = TRUE, repel = TRUE, label.size = 2.5) + 
  theme_minimal() +
  labs(title = 'Cell types') +
  theme(axis.line = element_line(colour = "grey83", linewidth=1.1),
          panel.border = element_rect(colour = "grey90", fill=NA, size=0.7),
          panel.grid.major = element_line(color = "grey96"),
          aspect.ratio = 1/1.05) +
  NoLegend()

p1 + p2


```

```{r}
bm_data <- RunUMAP(bm_data, reduction = 'pca', dims = 1:30, assay = 'RNA', 
              reduction.name = 'rna.umap', reduction.key = 'rnaUMAP_')
bm_data <- RunUMAP(bm_data, reduction = 'apca', dims = 1:18, assay = 'ADT', 
              reduction.name = 'adt.umap', reduction.key = 'adtUMAP_')

```

```{r, fig.width= 10}

p3 <- DimPlot(bm_data, reduction = 'rna.umap', group.by = 'celltype.l2', label = TRUE, 
              repel = TRUE, label.size = 2.5) + 
  theme_minimal() +
  labs(title = 'RNA cell types') +
  theme(axis.line = element_line(colour = "grey83", linewidth=1.1),
          panel.border = element_rect(colour = "grey90", fill=NA, size=0.7),
          panel.grid.major = element_line(color = "grey96"),
          aspect.ratio = 1/1.05)+
  NoLegend()
p4 <- DimPlot(bm_data, reduction = 'adt.umap', group.by = 'celltype.l2', label = TRUE, 
              repel = TRUE, label.size = 2.5) + 
  theme_minimal() +
  labs(title = 'ADT cell types') +
  theme(axis.line = element_line(colour = "grey83", linewidth=1.1),
          panel.border = element_rect(colour = "grey90", fill=NA, size=0.7),
          panel.grid.major = element_line(color = "grey96"),
          aspect.ratio = 1/1.05)+
  NoLegend()
p3 + p4

```

```{r, fig.width= 10}

p5 <- FeaturePlot(bm_data, features = c("adt_CD45RA","adt_CD16","adt_CD161"),
                  reduction = 'wnn.umap', max.cutoff = 2, 
                  cols = c("grey","darkgreen"), ncol = 3)
p6 <- FeaturePlot(bm_data, features = c("rna_TRDC","rna_MPO","rna_AVP"), 
                  reduction = 'wnn.umap', max.cutoff = 3, ncol = 3)
p5 / p6

```

```{r, fig.width= 9}
 VlnPlot(bm_data, features = "RNA.weight", group.by = 'celltype.l2', sort = TRUE, pt.size = 0.1) +
  NoLegend()

```

```{r}
compute_silhouette(bm_data@reductions$rna.umap@cell.embeddings, bm_data@meta.data$celltype.l2, result_format = 'plot') +
  labs(title = 'Silhouette coef. of RNA UMAP per cell type')

```

```{r}
compute_silhouette(bm_data@reductions$adt.umap@cell.embeddings, bm_data@meta.data$celltype.l2, result_format = 'plot') +
  labs(title = 'Silhouette coef. of ADT UMAP per cell type')

```

```{r}
compute_silhouette(bm_data@reductions$wnn.umap@cell.embeddings, bm_data@meta.data$celltype.l2, result_format = 'plot') +
  labs(title = 'Silhouette coef. of WNN UMAP per cell type')

```

```{r}

bm_mofa <- MOFA2::create_mofa_from_Seurat(bm_data, 
                                          groups = NULL, 
                                          assays = c('RNA', 'ADT'),
                                          features = list(bm_data@assays$RNA@features@.Data,
                                                          bm_data@assays$ADT@features@.Data))

# need to use stochastic variational inference since our data is too big.
params <- MOFA2::get_default_training_options(bm_mofa)
params$stochastic <- T

bm_mofa <- MOFA2::prepare_mofa(bm_mofa, training_options = params)
bm_mofa <- MOFA2::run_mofa(bm_mofa, use_basilisk = T)

# saving the MOFA obj onto vast since this took 1.5hrs to finish

# saveRDS(bm_mofa, file = '/vast/scratch/users/liu.ne/bm_mofa_all_features.rds')

bm_mofa <- readRDS('/vast/scratch/users/liu.ne/bm_mofa_all_features.rds')

```

```{r}
p1 <- MOFA2::plot_variance_explained(bm_mofa)

p1

```

Now run UMAP on the MOFA factors and plot

```{r}

bm_data <- MOFA2::add_mofa_factors_to_seurat(mofa_object = bm_mofa, seurat_object =  bm_data, 
                                  views = 'all', factors = 'all')

bm_data <- RunUMAP(bm_data, reduction = 'MOFA', dims = c(1:25)[-9], reduction.name = 'MOFA_UMAP')

```

```{r, fig.width= 9}

DimPlot(bm_data, reduction = 'MOFA_UMAP', group.by = 'celltype.l2', label = T,
                      repel = TRUE, label.size = 2.5) + 
  theme_minimal() +
  labs(title = 'MOFA cell types') +
  theme(axis.line = element_line(colour = "grey83", linewidth=1.1),
          panel.border = element_rect(colour = "grey90", fill=NA, size=0.7),
          panel.grid.major = element_line(color = "grey96"),
          aspect.ratio = 1/1.05) +
  NoLegend()


```

```{r}
compute_silhouette(bm_data@reductions$MOFA_UMAP@cell.embeddings, bm_data@meta.data$celltype.l2, 
                   result_format = 'plot')


```


To benchmark with other methods such as totalVI, we need to use the reticulate package to operate python in R. 

```{r}
library(reticulate)
library(anndata)
library(sceasy)
library(SeuratDisk)

# devtools::install_github("cellgeni/sceasy")
# use_condaenv('scMultiOmics_normalization')
# reticulate::conda_install(envname = 'scMultiOmics_normalization', packages = 'loompy')
# loompy <- reticulate::import('loompy')

# reticulate::py_install('scvi')
# reticulate::py_install('scanpy')
# reticulate::conda_install(packages = 'scanpy')
# reticulate::conda_install(packages = 'scvi-tools')
# scanpy <- reticulate::import_from_path('scanpy', path = "/stornext/System/data/apps/miniconda3/miniconda3-latest/bin/conda", convert = F)
# scvi <- reticulate::import('scvi-tools', convert = F)

# all this will fail on the hpc. it is futile.

# BiocManager::install("zellkonverter", force = T)
library(zellkonverter)

test <- Seurat::as.SingleCellExperiment(bm_data)
DefaultAssay(bm_data) <- 'RNA'
test1 <- Seurat::as.SingleCellExperiment(bm_data)
zellkonverter::writeH5AD(test, file = '/vast/scratch/users/liu.ne/bm_ADT.h5ad')
zellkonverter::writeH5AD(test1, file = '/vast/scratch/users/liu.ne/bm_RNA.h5ad')


```

Trying to run tilted-CCA

```{r}
rna_matrix <- Matrix::t(bm_data[['RNA']]$scale.data)
adt_matrix <- Matrix::t(bm_data[['ADT']]$scale.data)

set.seed(10)
multi_SVD <- tiltedCCA::create_multiSVD(mat_1 = rna_matrix, mat_2 = adt_matrix, 
                                        dims_1 = 1:30, dims_2 = 1:18,
                                        scale_1 = F, scale_2 = F)

Seurat::DefaultAssay(bm_data) <- 'RNA'
bm_data <- Seurat::FindNeighbors(bm_data, reduction = 'pca', dims = 1:30, return.neighbor = T)
bm_data <- Seurat::FindClusters(bm_data, graph.name = 'RNA_snn', resolution = 0.25)
Seurat::DefaultAssay(bm_data) <- 'ADT'
bm_data <- Seurat::FindNeighbors(bm_data, reduction = 'apca', dims = 1:18, return.neighbor = T)
bm_data <- Seurat::FindClusters(bm_data, graph.name = 'ADT_snn', resolution = 0.25)


multi_SVD <- tiltedCCA::form_metacells(multi_SVD,
                                       large_clustering_1 = bm_data$RNA_snn_res.0.25,
                                       large_clustering_2 = bm_data$ADT_snn_res.0.25)

multi_SVD <- tiltedCCA::compute_snns(multi_SVD, num_neigh = 30, latent_k = 20)

multi_SVD <- tiltedCCA::tiltedCCA(multi_SVD, verbose = 1)

# This part takes VERY long (more than 6 hours). 
multi_SVD <- tiltedCCA::fine_tuning(multi_SVD, verbose = 1) |> tiltedCCA_decomposition(verbose = 1)

saveRDS(multi_SVD, file = '/vast/scratch/users/liu.ne/bm_CITEseq_tiltedCCA.rds')


```

```{r}
bm_data[['tcca_common']] <- tiltedCCA::create_SeuratDim(multi_SVD, what = 'common', seurat_obj = bm_data, 
                                                        aligned_umap_assay = 'MOFA_UMAP', verbose = 1)

bm_data[['tcca_distinct_rna']] <- tiltedCCA::create_SeuratDim(multi_SVD, what = 'distinct_1', seurat_obj = bm_data, 
                                                        aligned_umap_assay = 'MOFA_UMAP', verbose = 1)

bm_data[['tcca_distinct_adt']] <- tiltedCCA::create_SeuratDim(multi_SVD, what = 'distinct_2', seurat_obj = bm_data, 
                                                        aligned_umap_assay = 'MOFA_UMAP', verbose = 1, seurat_assay = 'ADT')

```

```{r, fig.width= 10}

DimPlot(bm_data, reduction = 'tcca_common', group.by = 'celltype.l2', label = T, repel = T, label.size = 2.5)+
  theme_minimal() +
  labs(title = 't-CCA common cell types') +
  theme(axis.line = element_line(colour = "grey83", linewidth=1.1),
          panel.border = element_rect(colour = "grey90", fill=NA, size=0.7),
          panel.grid.major = element_line(color = "grey96"),
          aspect.ratio = 1/1.05) +
  NoLegend()

```

```{r}
compute_silhouette(bm_data[['tcca_common']]@cell.embeddings, label_vector = bm_data$celltype.l2, result_format = 'plot')

```




```{r, fig.width= 10}

p1 <- DimPlot(bm_data, reduction = 'tcca_distinct_rna', group.by = 'celltype.l2', label = T, repel = T, label.size = 2.5)+
  theme_minimal() +
  labs(title = 't-CCA RNA distinct cell types') +
  theme(axis.line = element_line(colour = "grey83", linewidth=1.1),
          panel.border = element_rect(colour = "grey90", fill=NA, size=0.7),
          panel.grid.major = element_line(color = "grey96"),
          aspect.ratio = 1/1.05) +
  NoLegend()

p2 <- DimPlot(bm_data, reduction = 'tcca_distinct_adt', group.by = 'celltype.l2', label = T, repel = T, label.size = 2.5)+
  theme_minimal() +
  labs(title = 't-CCA ADT distinct cell types') +
  theme(axis.line = element_line(colour = "grey83", linewidth=1.1),
          panel.border = element_rect(colour = "grey90", fill=NA, size=0.7),
          panel.grid.major = element_line(color = "grey96"),
          aspect.ratio = 1/1.05) +
  NoLegend()

p1 + p2

```

```{r}
compute_silhouette(bm_data[['tcca_distinct_rna']]@cell.embeddings, label_vector = bm_data$celltype.l2, result_format = 'plot')
```
```{r}
compute_silhouette(bm_data[['tcca_distinct_adt']]@cell.embeddings, label_vector = bm_data$celltype.l2, result_format = 'plot')

```

```{r, fig.width= 8}

library(parallel)

all_silhouette_scores <- parallel::mclapply(list(bm_data@reductions$rna.umap@cell.embeddings,
                                  bm_data@reductions$adt.umap@cell.embeddings,
                                  bm_data@reductions$wnn.umap@cell.embeddings,
                                  bm_data@reductions$MOFA_UMAP@cell.embeddings,
                                  bm_data[['tcca_common']]@cell.embeddings, 
                                  bm_data[['tcca_distinct_rna']]@cell.embeddings, 
                                  bm_data[['tcca_distinct_adt']]@cell.embeddings), 
                             function(x){compute_silhouette(matrix = x, label_vector = bm_data$celltype.l2, 
                                                            result_format = 'per_cluster')})

all_silhouette_scores <- do.call(rbind, all_silhouette_scores)
all_silhouette_scores$algorithm <- rep(c('raw_RNA', 'raw_ADT', 'WNN', 'MOFA', 't-CCA_common', 't-CCA_unique_RNA', 't-CCA_unique_ADT'), each = 27)

plot_boxplot_categorical(all_silhouette_scores$silhouette_score, all_silhouette_scores$algorithm, names = c('sihouette score', 'algorithm')) +
  theme(axis.text.x = element_text(size = 10,angle = 45,hjust = 1))

```

```{r, fig.width= 8}
# install.packages('ggbeeswarm')
library(ggbeeswarm)

plot_violin(all_silhouette_scores$silhouette_score, all_silhouette_scores$algorithm, names = c('silhouette','algorithm')) + 
  coord_cartesian(ylim = c(-1, 1.4))

```



```{r}
# devtools::install_github("immunogenomics/lisi")
library(lisi)

LISI_scores <- compute_lisi(bm_data@reductions$pca@cell.embeddings[,1:20], 
                            meta_data = bm_data@meta.data, 
                            label_colnames = c('lane', 'donor', 'celltype.l2')) |> cbind.data.frame(dplyr::select(bm_data@meta.data, c('lane', 'donor', 'celltype.l2')))

colnames(LISI_scores) <- c('lane_score', 'donor_score', 'celltype_score', 'lane', 'donor', 'celltype')

```

```{r, fig.width= 12}
plot_violin(LISI_scores$donor_score, LISI_scores$donor, c('LISI for lane', 'lane'), overlay_type = 'boxplot')

```

```{r, fig.width= 12}
# save.image(file= '/vast/scratch/users/liu.ne/bm_CITEseq_backup.RData')
# load('/vast/scratch/users/liu.ne/bm_CITEseq_backup.RData')

adt_plot_data <- tidyr::pivot_longer(as.data.frame(bm_data@assays$ADT@layers$scale.data), 
                                     cols = everything())
adt_plot_data$cell_labels <- rep(bm_data$celltype.l2, each = 25)

plot_violin(adt_plot_data$value, adt_plot_data$cell_labels, c('adt', 'celltype'))

```

```{r, fig.width= 12}
adt_plot_data <- ADTnorm::arcsinh_transform(t(as.matrix(bm_data@assays$ADT@layers$counts))) %>% as.data.frame () %>% tidyr::pivot_longer(cols = everything())

adt_plot_data$cell_labels <- rep(bm_data$celltype.l2, 25)

plot_violin(adt_plot_data$value, adt_plot_data$cell_labels, c('adt', 'celltype'))

```

```{r, fig.height= 10, fig.width= 9}
library(ggridges)

adt_arcsinh_data <- ADTnorm::arcsinh_transform((as.matrix(bm_data@assays$ADT@layers$counts)) %>% as.data.frame())
rownames(adt_arcsinh_data) <- bm_data@assays$ADT@meta.data$var.features

p <- plot_ridgeplot(matrix= adt_arcsinh_data[c('CD8'),], label_vector = bm_data$celltype.l2)

p

```


```{r}
library(matlib)
a <- as.matrix(adt_matrix[1:30, 1:7])

View((t(a) %*% a))

View(inv(t(a) %*% a))


```


```{r}


plot_UMAP <- function(matrix, metadata_vector, title = 'UMAP', aspect_ratio = 1/1.1, run_umap = T, label_is_continuous = F, 
                      continuous_var_upper_lim = NULL){
  # taking a matrix and a vector of metadata, plot UMAP of the matrix colored by the groups in the metadata vector
  
  if(run_umap){
  umap_result = umap(t(matrix))
  df = data.frame(umap_result$layout)}
  if(!run_umap){df <- as.data.frame(matrix)}
  colnames(df) = c("UMAP1", "UMAP2")
  
  if(!is.null(continuous_var_upper_lim)){
    if(class(continuous_var_upper_lim) != 'numeric'){stop("You didn't enter a numerical value for the continous variable uppe limit. Please only enter numbers.")}
    else(metadata_vector <- lapply(metadata_vector,
                                   function(x) ifelse(x > continuous_var_upper_lim,
                                                      continuous_var_upper_lim,
                                                      x)) %>% unlist())}
  
  df$metadata = metadata_vector 
  
  if(!label_is_continuous){
  ggplot(df, aes(x = UMAP1, y = UMAP2, color = metadata)) +
    geom_point(size = 0.07) +
    ggtitle(title) +
    theme_minimal() +
    theme(axis.line = element_line(colour = "grey83", linewidth = 1.1),
          panel.border = element_rect(colour = "grey90", fill=NA, size=0.7),
          panel.grid.major = element_line(color = "grey96"),
          aspect.ratio = aspect_ratio)
  }
  if(label_is_continuous){
    ggplot(df, aes(x = UMAP1, y = UMAP2, color = metadata)) +
    geom_point(size = 0.07) +
    scale_fill_viridis() +
    scale_color_viridis() +
    ggtitle(title) +
    theme_minimal() +
    theme(axis.line = element_line(colour = "grey83", linewidth = 1.1),
          panel.border = element_rect(colour = "grey90", fill=NA, size=0.7),
          panel.grid.major = element_line(color = "grey96"),
          aspect.ratio = 1/1.05)
  }
  
}

```


```{r, fig.width= 9}
# Normalize with ADTnorm, CLR & DSB
adt_data <- as.matrix(bm_data@assays$ADT@layers$counts)
rownames(adt_data) <- bm_data@assays$ADT@meta.data$var.features

adt_counts_umap <- umap(t(adt_data))$layout %>% as.data.frame()

plot_UMAP(adt_counts_umap, metadata_vector = bm_data$celltype.l2, title = 'UMAP of ADT raw counts', run_umap = F)


```

```{r}

df <- adt_counts_umap
df$metadata <- bm_data$nCount_RNA

lim = 4000
df$metadata <- lapply(df$metadata, function(x) ifelse(x > lim, lim, x)) %>% unlist()


ggplot(df, aes(x = V1, y = V2, color = metadata)) +
    geom_point(size = 0.07) +
    scale_fill_viridis() +
    scale_color_viridis() +
    ggtitle('UMAP ADT raw counts with RNA libsize') +
    theme_minimal() +
    theme(axis.line = element_line(colour = "grey83", linewidth = 1.1),
          panel.border = element_rect(colour = "grey90", fill=NA, size=0.7),
          panel.grid.major = element_line(color = "grey96"),
          aspect.ratio = 1/1.05)


```
```{r}
df <- adt_counts_umap
df$metadata <- bm_data$nCount_ADT

lim = 10000
df$metadata <- lapply(df$metadata, function(x) ifelse(x > lim, lim, x)) %>% unlist()

plot_UMAP(df, bm_data$nCount_ADT, title = 'UMAP ADT raw counts with total ADT counts', 
          run_umap = F, label_is_continuous = T, continuous_var_upper_lim = 10000)

```




```{r}

compute_silhouette((adt_data), run_dim_reduction = 'umap', bm_data$celltype.l2, result_format = 'plot') +
  ggtitle('ADT raw counts')


```





```{r}

compute_silhouette((bm_data@assays$ADT$data), run_dim_reduction = 'umap', bm_data$celltype.l2, result_format = 'plot') +
  ggtitle('ADT CLR')


```



```{r}
adt_dsb <- dsb::ModelNegativeADTnorm(t(adt_data), use.isotype.control = F)

compute_silhouette(t(adt_dsb), run_dim_reduction = 'umap', bm_data$celltype.l2, result_format = 'plot') +
  ggtitle('ADT DSB')

```





```{r, fig.width= 10}
adt_adtnorm <- ADTnorm(t(adt_data), bm_data@meta.data)




```




```{r}

test <- Seurat::Read10X_h5(file = '/vast/scratch/users/liu.ne/malt_10k_protein_v3_raw_feature_bc_matrix.h5')

```




