---
title: "WNN CITE seq & 10x Multiome"
author: "Neal Liu"
date: "2024-02-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries & our own helper functions

```{r}

library(Seurat)
library(SeuratData)
library(cowplot)
library(dplyr)
library(Signac)
library(EnsDb.Hsapiens.v86)
library(ggplot2)

source('Helper_functions.R')

# Code for fixing the weird glpk.h not found error when installing Seurat
# Sys.setenv(LIBRARY_PATH = "/stornext/System/data/tools/glpk/glpk-4.65/lib:$LIBRARY_PATH")
# Sys.setenv(CPATH = "/stornext/System/data/tools/glpk/glpk-4.65/include:$CPATH")
# Sys.setenv(LD_LIBRARY_PATH = "/stornext/System/data/tools/glpk/glpk-4.65/lib:$LD_LIBRARY_PATH")


```

Get the bone marrow CITEseq data from seurat and 10x multiome RNA+ATAC data on the VAST scratch on the HPC

```{r}
SeuratData::InstallData("bmcite", destdir = '/vast/scratch/users/liu.ne')
bm_data <- LoadData(ds = "bmcite")
multiome_data <- Read10X_h5("/vast/scratch/users/liu.ne/pbmc_granulocyte_sorted_10k_filtered_feature_bc_matrix.h5")

```


```{r}
DefaultAssay(bm_data) <- 'RNA'
bm_data <- NormalizeData(bm_data) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA()
```


```{r}
DefaultAssay(bm_data) <- 'ADT'
# we will use all ADT features for dimensional reduction
# we set a dimensional reduction name to avoid overwriting the 
VariableFeatures(bm_data) <- rownames(bm_data[["ADT"]])
bm_data <- NormalizeData(bm_data, normalization.method = 'CLR', margin = 2) %>% 
  ScaleData() %>% RunPCA(reduction.name = 'apca')

```

```{r}
# Identify multimodal neighbors. These will be stored in the neighbors slot, 
# and can be accessed using bm[['weighted.nn']]
# The WNN graph can be accessed at bm[["wknn"]], 
# and the SNN graph used for clustering at bm[["wsnn"]]
# Cell-specific modality weights can be accessed at bm$RNA.weight
bm_data <- FindMultiModalNeighbors(
  bm_data, reduction.list = list("pca", "apca"), 
  dims.list = list(1:30, 1:18), modality.weight.name = "RNA.weight"
)

```

```{r}
bm_data <- RunUMAP(bm_data, nn.name = "weighted.nn", reduction.name = "wnn.umap", reduction.key = "wnnUMAP_")
bm_data <- FindClusters(bm_data, graph.name = "wsnn", algorithm = 3, resolution = 2, verbose = FALSE)

```

```{r, fig.width= 10}

p1 <- DimPlot(bm_data, reduction = 'wnn.umap', label = TRUE, repel = TRUE, label.size = 2.5) + 
  theme_minimal() +
  labs(title = 'Clusters?') +
  theme(axis.line = element_line(colour = "grey83", linewidth=1.1),
          panel.border = element_rect(colour = "grey90", fill=NA, size=0.7),
          panel.grid.major = element_line(color = "grey96"),
          aspect.ratio = 1/1.05)+
  NoLegend()
p2 <- DimPlot(bm_data, reduction = 'wnn.umap', group.by = 'celltype.l2', label = TRUE, repel = TRUE, label.size = 2.5) + 
  theme_minimal() +
  labs(title = 'Cell types') +
  theme(axis.line = element_line(colour = "grey83", linewidth=1.1),
          panel.border = element_rect(colour = "grey90", fill=NA, size=0.7),
          panel.grid.major = element_line(color = "grey96"),
          aspect.ratio = 1/1.05) +
  NoLegend()

p1 + p2


```

```{r}
bm_data <- RunUMAP(bm_data, reduction = 'pca', dims = 1:30, assay = 'RNA', 
              reduction.name = 'rna.umap', reduction.key = 'rnaUMAP_')
bm_data <- RunUMAP(bm_data, reduction = 'apca', dims = 1:18, assay = 'ADT', 
              reduction.name = 'adt.umap', reduction.key = 'adtUMAP_')

```

```{r, fig.width= 10}
p3 <- DimPlot(bm_data, reduction = 'rna.umap', group.by = 'celltype.l2', label = TRUE, 
              repel = TRUE, label.size = 2.5) + 
  theme_minimal() +
  labs(title = 'RNA cell types') +
  theme(axis.line = element_line(colour = "grey83", linewidth=1.1),
          panel.border = element_rect(colour = "grey90", fill=NA, size=0.7),
          panel.grid.major = element_line(color = "grey96"),
          aspect.ratio = 1/1.05)+
  NoLegend()
p4 <- DimPlot(bm_data, reduction = 'adt.umap', group.by = 'celltype.l2', label = TRUE, 
              repel = TRUE, label.size = 2.5) + 
  theme_minimal() +
  labs(title = 'ADT cell types') +
  theme(axis.line = element_line(colour = "grey83", linewidth=1.1),
          panel.border = element_rect(colour = "grey90", fill=NA, size=0.7),
          panel.grid.major = element_line(color = "grey96"),
          aspect.ratio = 1/1.05)+
  NoLegend()
p3 + p4

```



















```{r}
remotes::install_github("mojaveazure/seurat-disk")
library(SeuratDisk)
loom_data <- SeuratDisk::Connect(filename = "/vast/scratch/users/liu.ne/l5_all.loom", mode = 'r')
mouse_cortex_data <- as.Seurat(loom_data)


```











